name: cli
version: 0.0.2
author: Sean Eagan <seaneagan1@gmail.com>
description: Iinterfaces for sending and receiving cli commands.
homepage: http://github.com/seaneagan/cli
dependencies:
  meta: any
dev_dependencies:
  unittest: any
